"""Stage D — Anthropic Contextual Retrieval: a per-chunk context, pinned to disk.

Dev-only ([corpus] extra). For each chunk, Claude Haiku 4.5 is asked to situate
it inside its context window (see context_windows.py); the resulting context is
prepended to the chunk at index time so BM25 and (Phase 2) the embedder see a
self-describing passage.

Contexts are PINNED to corpus/contexts/<manifest-slug>.json keyed by chunk_id and
committed to git, so a rebuild -- on any machine, with no API key -- reuses them
and stays deterministic. Context is never an input to chunk_id, so LLM
non-determinism cannot affect IDs (ingest design spec section 5).
"""

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from ..models.ids import chunk_id as mk_chunk_id

PROMPT_VERSION = 1  # bump to invalidate every pinned context


def text_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def contexts_path_for(contexts_dir, slug: str) -> Path:
    return Path(contexts_dir) / f"{slug}.json"


def load_pin_file(contexts_dir, slug: str) -> dict:
    p = contexts_path_for(contexts_dir, slug)
    if not p.exists():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


def save_pin_file(contexts_dir, slug: str, record: dict) -> Path:
    p = contexts_path_for(contexts_dir, slug)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return p


def valid_pinned(record: dict, records, *, canonical_url: str, version: str,
                 model: str, prompt_version: int) -> dict:
    """{chunk_id: context} for pins still valid for these records.

    Drops everything when the file was generated by a different model or prompt
    version, and drops any single entry whose chunk text has changed since it was
    pinned (chunk_id does not depend on text, so this hash is the only guard).
    """
    if not record:
        return {}
    if record.get("model") != model or record.get("prompt_version") != prompt_version:
        return {}
    pinned = record.get("contexts") or {}
    out = {}
    for rec in records:
        cid = mk_chunk_id(canonical_url, version, rec.chunk_index)
        entry = pinned.get(cid)
        if not entry or not isinstance(entry, dict):
            continue
        context = (entry.get("context") or "").strip()
        if not context or entry.get("text_sha256") != text_sha256(rec.text):
            continue
        out[cid] = context
    return out
