"""Stage D — Anthropic Contextual Retrieval: a per-chunk context, pinned to disk.

Dev-only ([corpus] extra). For each chunk, Claude Haiku 4.5 is asked to situate
it inside its context window (see context_windows.py); the resulting context is
prepended to the chunk at index time so BM25 and (Phase 2) the embedder see a
self-describing passage.

Contexts are PINNED to corpus/contexts/<manifest-slug>.json keyed by chunk_id and
committed to git, so a rebuild -- on any machine, with no API key -- reuses them
and stays deterministic. Context is never an input to chunk_id, so LLM
non-determinism cannot affect IDs (ingest design spec section 5).
"""

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from ..db import ops
from ..models.ids import chunk_id as mk_chunk_id
from .context_windows import build_windows, est_tokens

PROMPT_VERSION = 1  # bump to invalidate every pinned context


def text_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def contexts_path_for(contexts_dir, slug: str) -> Path:
    return Path(contexts_dir) / f"{slug}.json"


def load_pin_file(contexts_dir, slug: str) -> dict:
    """The pinned record for one document, or {} when absent or unreadable.

    A corrupt or truncated pin file degrades to "no pins" -- the contexts are
    simply regenerated -- rather than raising and taking the whole document out
    of the build. Consistent with valid_pinned, which drops every other malformed
    shape instead of failing.
    """
    p = contexts_path_for(contexts_dir, slug)
    if not p.exists():
        return {}
    try:
        record = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError, OSError):
        return {}
    return record if isinstance(record, dict) else {}


def save_pin_file(contexts_dir, slug: str, record: dict) -> Path:
    """Write the pin file atomically (tmp + os.replace).

    Pins are now flushed once per window rather than once per document, which
    multiplies the number of writes during the long generation pass; a hard kill
    landing inside a plain write would leave a truncated file and forfeit that
    document's paid-for contexts. os.replace is atomic on the same volume, so a
    reader sees either the old file or the new one, never a half-written one.
    """
    p = contexts_path_for(contexts_dir, slug)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp, p)
    return p


def valid_pinned(record: dict, records, *, canonical_url: str, version: str,
                 model: str, prompt_version: int) -> dict:
    """{chunk_id: context} for pins still valid for these records.

    Drops everything when the file was generated by a different model or prompt
    version, and drops any single entry whose chunk text has changed since it was
    pinned (chunk_id does not depend on text, so this hash is the only guard).
    """
    if not record:
        return {}
    if record.get("model") != model or record.get("prompt_version") != prompt_version:
        return {}
    pinned = record.get("contexts") or {}
    out = {}
    for rec in records:
        cid = mk_chunk_id(canonical_url, version, rec.chunk_index)
        entry = pinned.get(cid)
        if not entry or not isinstance(entry, dict):
            continue
        context = (entry.get("context") or "").strip()
        if not context or entry.get("text_sha256") != text_sha256(rec.text):
            continue
        out[cid] = context
    return out


SYSTEM_PROMPT = (
    "You write short retrieval contexts for a search index. You are given an "
    "excerpt from a source document and one chunk taken from that excerpt. Write "
    "1-3 sentences (under 80 words) that situate the chunk within the document so "
    "it can be understood and retrieved on its own: name the document, the section "
    "or topic it belongs to, and any entity, definition, section number, or "
    "cross-reference the chunk depends on. Use only information present in the "
    "excerpt -- never add outside knowledge and never speculate. Respond with the "
    "context only: no preamble, no quotes, no markdown, no bullet points."
)

TASK_INSTRUCTION = (
    "Give a short context that situates this chunk within the document above, to "
    "improve search retrieval of the chunk. Answer only with the context."
)


def build_doc_header(doc_title: str, source_url: str) -> str:
    return f"# {doc_title}\nSource: {source_url}"


def build_messages(doc_header: str, window_text: str, chunk_text: str, *, cache_ttl: str) -> list:
    """One user message: [cached window prefix, volatile chunk suffix].

    The cache_control breakpoint goes on the FIRST block only. Render order is
    tools -> system -> messages, and caching is a prefix match, so this one
    breakpoint caches the system prompt and the window together; every chunk in
    the same window reproduces those bytes exactly and reads the cache.
    """
    return [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": f"{doc_header}\n\n<document_excerpt>\n{window_text}\n</document_excerpt>",
                    "cache_control": {"type": "ephemeral", "ttl": cache_ttl},
                },
                {
                    "type": "text",
                    "text": f"<chunk>\n{chunk_text}\n</chunk>\n\n{TASK_INSTRUCTION}",
                },
            ],
        }
    ]


def _usage_dict(usage) -> dict:
    return {
        "input_tokens": getattr(usage, "input_tokens", 0) or 0,
        "output_tokens": getattr(usage, "output_tokens", 0) or 0,
        "cache_creation_input_tokens": getattr(usage, "cache_creation_input_tokens", 0) or 0,
        "cache_read_input_tokens": getattr(usage, "cache_read_input_tokens", 0) or 0,
    }


class ContextGenerator:
    """The only place that calls the Anthropic API."""

    def __init__(self, client, cfg: dict):
        self._client = client
        self._model = cfg.get("model", "claude-haiku-4-5")
        self._max_tokens = int(cfg.get("max_tokens", 150))
        self._temperature = cfg.get("temperature", 0)
        self._cache_ttl = cfg.get("cache_ttl", "1h")

    def generate(self, doc_header: str, window_text: str, chunk_text: str) -> tuple:
        msg = self._client.messages.create(
            model=self._model,
            max_tokens=self._max_tokens,
            temperature=self._temperature,
            system=[{"type": "text", "text": SYSTEM_PROMPT}],
            messages=build_messages(doc_header, window_text, chunk_text, cache_ttl=self._cache_ttl),
        )
        text = "".join(
            b.text for b in msg.content if getattr(b, "type", None) == "text"
        ).strip()
        return text, _usage_dict(msg.usage)


def _credentials_resolved(client) -> bool:
    """True when the SDK resolved SOME authentication method for this client.

    Static credentials (ANTHROPIC_API_KEY / ANTHROPIC_AUTH_TOKEN) populate
    auth_headers; a stored `ant auth login` profile, OAuth, or workload-identity
    federation instead arrive as `credentials`/`custom_auth` and leave
    auth_headers EMPTY -- checking only auth_headers would reject a correctly
    authenticated user. Offline: touches no network.
    """
    try:
        if client.auth_headers:
            return True
    except Exception:  # noqa: BLE001 -- an unresolvable auth method means "no credentials"
        return False
    return (getattr(client, "credentials", None) is not None
            or getattr(client, "custom_auth", None) is not None)


def make_client(cfg: dict) -> tuple:
    """(client, reason). Returns (None, reason) when the SDK or credentials are absent.

    Constructing the client is NOT the credential check -- the SDK happily builds
    one with api_key=None and only raises at request time (verified on anthropic
    0.121.0). Resolution is probed separately by _credentials_resolved.
    """
    try:
        import anthropic  # lazy: [corpus] extra only; the pinned-context path must work without it
    except ImportError:
        return None, "the anthropic SDK is not installed (pip install -e \".[corpus]\")"
    # An identity-linked API key is rejected with a 400 unless every request names
    # the workspace it acts in ("anthropic-workspace-id is required when
    # authenticating with an identity-linked API key"). Sent as a default header
    # only when configured, so a plain key is unaffected.
    headers = {}
    workspace = (os.environ.get("ANTHROPIC_WORKSPACE_ID") or "").strip()
    if workspace and workspace != "PASTE_YOUR_WORKSPACE_ID_HERE":
        headers["anthropic-workspace-id"] = workspace
    try:
        client = anthropic.Anthropic(max_retries=int(cfg.get("max_retries", 5)),
                                     default_headers=headers or None)
    except Exception as exc:  # noqa: BLE001 -- any credential-resolution failure means "no client"
        return None, f"no Anthropic credentials resolved ({exc})"
    # Constructing is NOT the credential check: the SDK builds a client with
    # api_key=None and only raises at request time. Probe its own resolution
    # offline instead. Without this, a keyless build would call the API once per
    # chunk and log thousands of failures instead of skipping with one note.
    if not _credentials_resolved(client):
        return None, ("no Anthropic credentials resolved "
                      "(set ANTHROPIC_API_KEY or run `ant auth login`)")
    return client, "ok"


def _empty_usage() -> dict:
    return {"input_tokens": 0, "output_tokens": 0,
            "cache_creation_input_tokens": 0, "cache_read_input_tokens": 0, "calls": 0}


def contexts_for_document(slug: str, records, *, canonical_url: str, version: str,
                          doc_title: str, source_url: str, contexts_dir, cfg: dict,
                          client=None, force=False, log=None) -> dict:
    """Pinned-first contexts for one document; generates only what is missing.

    With client=None this is fully offline: valid pins are returned, missing
    chunks are counted, and nothing fails -- that is the no-API-key build path.
    """
    model = cfg.get("model", "claude-haiku-4-5")
    stats = {"contexts": {}, "pinned": 0, "generated": 0, "missing": 0,
             "errors": [], "usage": _empty_usage()}
    if not records:
        return stats

    pinned = {} if force else valid_pinned(
        load_pin_file(contexts_dir, slug), records,
        canonical_url=canonical_url, version=version,
        model=model, prompt_version=PROMPT_VERSION,
    )
    stats["contexts"].update(pinned)
    stats["pinned"] = len(pinned)

    windows = build_windows(records, cfg)
    by_index = {r.chunk_index: r for r in records}
    doc_header = build_doc_header(doc_title, source_url)
    generated = {}

    def _flush() -> None:
        """Persist what has been generated so far.

        Called after every window and again from a finally, so an interrupt or a
        crash mid-document keeps the contexts already paid for. Flushing only at
        the end meant a Ctrl-C inside the largest document (376 chunks, ~13% of
        the run) threw all of them away and re-paid on the next attempt.

        Always merges onto what is already pinned, force included: force means
        "regenerate rather than reuse", not "discard pins for chunks whose
        regeneration failed". Entries from THIS run win.
        """
        if not generated:
            return
        record = load_pin_file(contexts_dir, slug)
        merged = dict(record.get("contexts") or {}) if record.get("model") == model \
            and record.get("prompt_version") == PROMPT_VERSION else {}
        merged.update(generated)
        save_pin_file(contexts_dir, slug, {
            "doc_id": slug,
            "model": model,
            "prompt_version": PROMPT_VERSION,
            "generated_at": _now(),
            "contexts": merged,
        })

    try:
        _generate(windows, by_index, doc_header, generated, stats,
                  slug=slug, canonical_url=canonical_url, version=version,
                  cfg=cfg, client=client, log=log, flush=_flush)
    finally:
        _flush()
    return stats


def _generate(windows, by_index, doc_header, generated, stats, *, slug, canonical_url,
              version, cfg, client, log, flush) -> None:
    for window in windows:
        todo = [
            i for i in window.chunk_indices
            if mk_chunk_id(canonical_url, version, i) not in stats["contexts"]
        ]
        if not todo:
            continue
        if client is None:
            stats["missing"] += len(todo)
            continue
        gen = ContextGenerator(client, cfg)
        # Sequential on purpose: the first call in a window writes the cache and the
        # rest read it. Concurrent calls sharing a prefix would all miss the cache.
        for idx in todo:
            cid = mk_chunk_id(canonical_url, version, idx)
            try:
                context, usage = gen.generate(doc_header, window.text, by_index[idx].text)
            except Exception as exc:  # noqa: BLE001 -- one bad chunk must not abort the run
                stats["errors"].append({"chunk_index": idx, "error": f"{type(exc).__name__}: {exc}"})
                stats["missing"] += 1
                continue
            for k in ("input_tokens", "output_tokens",
                      "cache_creation_input_tokens", "cache_read_input_tokens"):
                stats["usage"][k] += usage[k]
            stats["usage"]["calls"] += 1
            if not context:
                stats["errors"].append({"chunk_index": idx, "error": "empty context returned"})
                stats["missing"] += 1
                continue
            stats["contexts"][cid] = context
            generated[cid] = {
                "context": context,
                "text_sha256": text_sha256(by_index[idx].text),
                "window_index": window.window_index,
            }
            stats["generated"] += 1
            if log is not None:
                log(f"  [{slug}] chunk {idx} w{window.window_index} "
                    f"cache_read={usage['cache_read_input_tokens']}")
        flush()   # per window: never lose more than one window's spend


def estimate_document(records, cfg: dict, *, doc_header_len: int = 64) -> dict:
    """Offline projection of what contextualizing these records will cost.

    This is a FLOOR, not a ceiling. It prices each cacheable window as one
    uninterrupted run -- a single cache write amortized over (k-1) reads -- and
    assumes every call succeeds on the first attempt. A run that is interrupted
    and resumed after the cache TTL expires, or split across sessions with
    --only, pays another unamortized cache write for each partially-completed
    window; SDK retries after a 429/5xx also re-bill their input. Token counts
    are a chars/chars_per_token approximation, not Claude's tokenizer.
    """
    cpt = int(cfg.get("chars_per_token", 4))
    min_cacheable = int(cfg.get("min_cacheable_tokens", 4096))
    out_per_chunk = int(cfg.get("max_tokens", 150))
    system_tokens = est_tokens(SYSTEM_PROMPT, cpt) + est_tokens("x" * doc_header_len, cpt)
    instruction_tokens = est_tokens(TASK_INSTRUCTION, cpt)

    totals = {"windows": 0, "chunks": 0, "cacheable_windows": 0, "input_tokens": 0,
              "cache_write_tokens": 0, "cache_read_tokens": 0, "output_tokens": 0}
    by_index = {r.chunk_index: r for r in records}
    for window in build_windows(records, cfg):
        prefix = system_tokens + window.est_tokens
        k = len(window.chunk_indices)
        totals["windows"] += 1
        totals["chunks"] += k
        if prefix >= min_cacheable:
            totals["cacheable_windows"] += 1
            totals["cache_write_tokens"] += prefix
            totals["cache_read_tokens"] += prefix * (k - 1)
        else:
            totals["input_tokens"] += prefix * k
        for i in window.chunk_indices:
            totals["input_tokens"] += est_tokens(by_index[i].text, cpt) + instruction_tokens
        totals["output_tokens"] += out_per_chunk * k

    p_in = float(cfg.get("price_in_per_mtok", 1.0))
    p_out = float(cfg.get("price_out_per_mtok", 5.0))
    w_mult = float(cfg.get("cache_write_multiplier", 2.0))
    r_mult = float(cfg.get("cache_read_multiplier", 0.1))
    totals["usd"] = round(
        (totals["input_tokens"] * p_in
         + totals["cache_write_tokens"] * p_in * w_mult
         + totals["cache_read_tokens"] * p_in * r_mult
         + totals["output_tokens"] * p_out) / 1_000_000,
        4,
    )
    return totals


def _is_suspicious(context: str, chunk_text: str) -> bool:
    words = context.split()
    if len(words) < 5 or len(words) > 120:
        return True
    return chunk_text.strip().startswith(context.strip())


def context_coverage(ckb_path) -> dict:
    """Context-quality gate over a built CKB."""
    conn = ops.get_db(ckb_path)
    try:
        rows = conn.execute(
            "SELECT chunk_id, text, context FROM chunks ORDER BY doc_id, chunk_index"
        ).fetchall()
    finally:
        conn.close()
    out = {"total": len(rows), "with_context": 0, "empty": [], "suspicious": []}
    for row in rows:
        context = (row["context"] or "").strip()
        if not context:
            out["empty"].append(row["chunk_id"])
            continue
        out["with_context"] += 1
        if _is_suspicious(context, row["text"]):
            out["suspicious"].append(row["chunk_id"])
    return out


def load_document(entry, raw_dir, parsed_dir, cfg: dict, *, reparse=False):
    """(meta, version, dl_doc, records, title) for one manifest entry.

    THE shared document loader: build.build_ckb and the contextualize CLI both
    call this, so the two cannot drift on how a document is parsed and chunked.
    Reads the committed corpus/parsed/ cache -- Docling only runs under reparse.
    """
    from .chunk import chunk_document
    from .fetch import read_meta
    from .parse import parse_source

    meta = read_meta(raw_dir, entry.doc_id)
    if meta is None:
        raise FileNotFoundError(f"no pin record for {entry.doc_id} (run fetch first)")
    raw_path = Path(raw_dir) / meta["raw_filename"]
    dl_doc = parse_source(entry.doc_id, raw_path, parsed_dir, cfg["parse"], force=reparse)
    records = chunk_document(dl_doc, cfg["chunk"])
    title = getattr(dl_doc, "name", None) or entry.doc_id
    return meta, meta["resolved_version"], dl_doc, records, title


def main(argv=None) -> int:
    from ..config import load_corpus_config
    from .manifest import load_manifest

    p = argparse.ArgumentParser(prog="python -m kbmcp.ingest.contextualize")
    p.add_argument("--manifest", default="corpus/manifest.yaml")
    p.add_argument("--raw-dir", default="corpus/raw")
    p.add_argument("--parsed-dir", default="corpus/parsed")
    p.add_argument("--contexts-dir", default=None, help="default: contextualize.contexts_dir")
    p.add_argument("--config", default="config/corpus_config.yaml")
    p.add_argument("--only", action="append", default=None, help="manifest slug; repeatable")
    p.add_argument("--force", action="store_true", help="regenerate even when pins are valid")
    p.add_argument("--estimate", action="store_true",
                   help="project cost only; no API calls, no pins")
    p.add_argument("--limit", type=int, default=None, help="stop after N documents")
    a = p.parse_args(argv)

    full = load_corpus_config(a.config)
    cfg = full.contextualize
    contexts_dir = a.contexts_dir or cfg.get("contexts_dir", "corpus/contexts")
    entries = [e for e in load_manifest(a.manifest) if not a.only or e.doc_id in set(a.only)]
    if a.limit:
        entries = entries[: a.limit]

    if a.estimate:
        grand = {"windows": 0, "chunks": 0, "cacheable_windows": 0, "input_tokens": 0,
                 "cache_write_tokens": 0, "cache_read_tokens": 0, "output_tokens": 0, "usd": 0.0}
        failed = 0
        for entry in entries:
            try:
                _, _, _, records, _ = load_document(entry, a.raw_dir, a.parsed_dir, full.raw)
            except Exception as exc:  # noqa: BLE001 -- one unloadable doc must not abort the pass
                print(f"  {entry.doc_id:42s} [skipped] {type(exc).__name__}: {exc}",
                      file=sys.stderr)
                failed += 1
                continue
            est = estimate_document(records, cfg)
            for k in grand:
                grand[k] += est[k]
            print(f"  {entry.doc_id:42s} {est['chunks']:4d} chunks {est['windows']:3d} win  "
                  f"${est['usd']:.4f}", file=sys.stderr)
        print(f"ESTIMATE  docs={len(entries)} chunks={grand['chunks']} "
              f"windows={grand['windows']} cacheable={grand['cacheable_windows']}",
              file=sys.stderr)
        print(f"ESTIMATE  input={grand['input_tokens']} "
              f"cache_write={grand['cache_write_tokens']} "
              f"cache_read={grand['cache_read_tokens']} output={grand['output_tokens']}",
              file=sys.stderr)
        print(f"ESTIMATE  USD={round(grand['usd'], 4)}"
              + (f"  ({failed} doc(s) skipped — estimate is incomplete)" if failed else ""),
              file=sys.stderr)
        print("ESTIMATE  NOTE: this is a floor, not a ceiling — it prices each window as one "
              "uninterrupted run. Resuming after the cache TTL expires (or splitting the run "
              "with --only) pays an extra unamortized cache write per partially-done window, "
              "and retries re-bill their input.", file=sys.stderr)
        return 0

    client, reason = make_client(cfg)
    if client is None:
        print(f"[error] cannot contextualize: {reason}", file=sys.stderr)
        print("        set ANTHROPIC_API_KEY (or run `ant auth login`), or use --estimate",
              file=sys.stderr)
        return 1

    totals = {"pinned": 0, "generated": 0, "missing": 0, "errors": 0}
    usage = _empty_usage()
    for entry in entries:
        try:
            _, version, _, records, title = load_document(entry, a.raw_dir, a.parsed_dir, full.raw)
        except Exception as exc:  # noqa: BLE001 -- never abort a paid run over one bad document
            print(f"  {entry.doc_id:42s} [error] {type(exc).__name__}: {exc}", file=sys.stderr)
            totals["errors"] += 1
            continue
        out = contexts_for_document(
            entry.doc_id, records, canonical_url=entry.url, version=version,
            doc_title=title, source_url=entry.url, contexts_dir=contexts_dir,
            cfg=cfg, client=client, force=a.force,
        )
        for k in ("pinned", "generated", "missing"):
            totals[k] += out[k]
        totals["errors"] += len(out["errors"])
        for k in usage:
            usage[k] += out["usage"][k]
        print(f"  {entry.doc_id:42s} pinned={out['pinned']:4d} "
              f"generated={out['generated']:4d} missing={out['missing']:3d} "
              f"errors={len(out['errors'])}", file=sys.stderr)
        for err in out["errors"]:
            print(f"    [error] chunk {err['chunk_index']}: {err['error']}", file=sys.stderr)

    print(f"contexts: pinned={totals['pinned']} generated={totals['generated']} "
          f"missing={totals['missing']} errors={totals['errors']}", file=sys.stderr)
    print(f"usage: calls={usage['calls']} input={usage['input_tokens']} "
          f"cache_write={usage['cache_creation_input_tokens']} "
          f"cache_read={usage['cache_read_input_tokens']} output={usage['output_tokens']}",
          file=sys.stderr)
    return 0 if not totals["errors"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
